general:
  seed: &seed 42
  fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  n_splits: 5
  n_jobs: 3
  save_name: ../data/output/submission.csv

model: onedcnn

# ↓ for neural network
pl_params:
  max_epochs: &max_epochs 200
  accelerator: auto
  accumulate_grad_batches: 1
  precision: 32 # 16 or 32
  deterministic: true
  benchmark: false
  logger: false
  enable_checkpointing: false
  enable_model_summary: false
  enable_progress_bar: true
  #limit_train_batches: 0.01 # for debug
  #limit_val_batches: 0.05 # for debug

early_stopping:
  patience: 10

criterion: RMSELoss
optimizer:
  name: RAdam
  params:
    lr: 1.0e-3
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: *max_epochs
    eta_min: 1.0e-5

train_loader:
  batch_size: 1024
  shuffle: true
  num_workers: 2
  pin_memory: true
  drop_last: false
valid_loader:
  batch_size: 1024
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
test_loader:
  batch_size: 1024
  shuffle: false
  num_workers: 2
  pin_memory: true
  drop_last: false
