general:
  seed: &seed 42
  fold: [0, 1, 2, 3, 4] # list (0-idx start) or null. set one element list, hold-out mode.
  n_splits: 5
  n_jobs: 3
  save_name: ../data/output/submission.csv

model: tabnet

tabnet_params:
  device_name: "auto"
  seed: *seed
  n_d: 8
  n_a: 8
  n_steps: 3
  gamma: 1.3
  mask_type: "sparsemax"
  verbose: 1
tabnet_train_params:
  eval_metric: [rmse]
  max_epochs: &max_epochs 200
  patience: 5
  batch_size: 1024
  virtual_batch_size: 128
  num_workers: 2
  drop_last: false

pretrain: true
tabnet_pretrain_params:
  device_name: "auto"
  seed: *seed
  n_d: 8
  n_a: 8
  n_steps: 3
  gamma: 1.3
  mask_type: "sparsemax"
  verbose: 1
tabnet_pretrain_train_params:
  max_epochs: *max_epochs
  patience: 5
  batch_size: 1024
  virtual_batch_size: 128
  pretraining_ratio: 0.5
  num_workers: 2
  drop_last: false

optimizer:
  name: RAdam
  params:
    lr: 2.0e-2
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: *max_epochs
    eta_min: 2.0e-4
